# Generated by Django 4.1 on 2022-09-04 11:02

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('modified', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=264)),
                ('client', models.CharField(blank=True, max_length=264, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('program_type', models.CharField(blank=True, choices=[('web', 'Website'), ('dsk', 'Dektop'), ('plg', 'Plugin'), ('oth', 'Other')], max_length=3, null=True)),
                ('production_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
