# Generated by Django 4.1.1 on 2022-09-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='picture_1',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='picture_3',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='picture_4',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='picture_5',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='picture_6',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='picture_7',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='picture_8',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='picture_9',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
    ]
