# Generated by Django 4.1.1 on 2022-09-06 11:45

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('modified', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('project_name', models.CharField(blank=True, max_length=264, null=True)),
                ('person_name', models.CharField(max_length=264)),
                ('comment', models.TextField()),
                ('picture', models.ImageField(default='comment/default/default.jpg', upload_to='comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamousCustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('modified', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('picture', models.ImageField(default='comment/default/default.jpg', upload_to='comment/logos/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
