# Generated by Django 4.1 on 2022-08-27 13:32

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('modified', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=264)),
                ('phone_number', models.CharField(max_length=13)),
                ('title', models.CharField(max_length=264)),
                ('description', models.TextField(blank=True, null=True)),
                ('checked', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
