# Generated by Django 4.2.8 on 2023-12-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='type',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
